PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

CONSTRUCT { ?class ?p ?o . }
WHERE {
    ?gard_class a owl:Class ;
        oboInOwl:hasDbXref ?gard ;
        rdfs:subClassOf* ?class .
    FILTER(CONTAINS(str(?gard), 'GARD'))

    ?class ?p ?o .
}
