# Return a list of all non-obsolete class IDs and labels

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX doid: <http://purl.obolibrary.org/obo/DOID_>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT ?id ?type ?label
WHERE {
    ?s a owl:Class ;
        rdfs:subClassOf+ doid:14566 .
	OPTIONAL { ?s oboInOwl:id ?id . }
    OPTIONAL {
        ?s rdfs:label ?label .
        BIND( ?l AS ?label )
        BIND( "preferred" AS ?type )
    }
    OPTIONAL {
        ?s oboInOwl:hasExactSynonym ?syn .
        BIND( ?syn AS ?label )
        BIND( "exact_synonym" AS ?type )
    }
    FILTER NOT EXISTS { ?s owl:deprecated ?obsolete . }
}
